import React, { useState } from 'react';
import Layout from '../components/layout/Layout';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { FileText, Download, CheckCircle, Calendar, Filter } from 'lucide-react';

export default function Reports() {
  const [downloading, setDownloading] = useState(null);

  const reportCategoryData = [
    { category: 'Financial', generated: 142 },
    { category: 'Security Audit', generated: 98 },
    { category: 'AI Telemetry', generated: 210 },
    { category: 'User Traffic', generated: 165 },
  ];

  const reportsList = [
    { id: 'REP-2026-08', title: 'Q3 Financial Revenue & SLA Compliance Audit', date: '2026-08-15', size: '14.2 MB', category: 'Financial' },
    { id: 'REP-2026-07', title: 'SOC2 Type II Cyber Security Threat Vector Log', date: '2026-08-01', size: '8.4 MB', category: 'Security Audit' },
    { id: 'REP-2026-06', title: 'Neura-LLM GPU Node VRAM Memory Telemetry', date: '2026-07-20', size: '22.1 MB', category: 'AI Telemetry' },
  ];

  const handleDownload = (id) => {
    setDownloading(id);
    setTimeout(() => setDownloading(null), 1500);
  };

  return (
    <Layout title="Executive Reports & Export Engine" breadcrumb="Home / System / Reports">
      <div className="space-y-6">
        {/* Reports Generated BarChart */}
        <div className="rounded-3xl glass-card p-4 sm:p-6 border border-white/10 space-y-4 min-w-0 overflow-hidden">
          <h3 className="text-base font-bold text-white flex items-center">
            <FileText className="w-5 h-5 text-neura-cyan mr-2" />
            <span>Reports Generated by Category (615 Total)</span>
          </h3>

          <div className="w-full h-48 sm:h-56 min-w-0">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={reportCategoryData} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.06)" />
                <XAxis dataKey="category" stroke="#64748b" tick={{ fill: '#94a3b8', fontSize: 10 }} />
                <YAxis stroke="#64748b" tick={{ fill: '#94a3b8', fontSize: 10 }} width={40} />
                <Tooltip
                  cursor={{ fill: 'transparent' }}
                  contentStyle={{
                    backgroundColor: '#0B1020',
                    borderColor: 'rgba(255,255,255,0.15)',
                    borderRadius: '12px',
                    color: '#fff'
                  }}
                />
                <Bar dataKey="generated" fill="#00f0ff" radius={[6, 6, 0, 0]} maxBarSize={28} name="Reports Count" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="rounded-3xl glass-card p-6 border border-white/10 space-y-4">
          <h3 className="text-base font-bold text-white">Downloadable System Reports</h3>
          <div className="space-y-3">
            {reportsList.map((r) => (
              <div key={r.id} className="p-4 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-between hover:border-neura-cyan/40 transition-all">
                <div className="space-y-1">
                  <span className="text-[10px] font-mono text-neura-cyan font-bold">{r.id} • {r.category}</span>
                  <h4 className="text-xs font-bold text-white">{r.title}</h4>
                  <span className="text-[10px] text-slate-400 font-mono block">{r.date} • {r.size}</span>
                </div>
                <button
                  onClick={() => handleDownload(r.id)}
                  className="px-4 py-2 rounded-xl bg-neura-cyan text-black font-bold text-xs shadow-glow-cyan flex items-center space-x-1.5"
                >
                  <Download className="w-4 h-4" />
                  <span>{downloading === r.id ? 'Exporting...' : 'Download PDF'}</span>
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </Layout>
  );
}
